version: "3.4"

services:
  fafnir:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
      labels:
        com.qwant.ci.job.id: ${CI_JOB_ID}
        com.qwant.ci.pipeline.id: ${CI_PIPELINE_ID}
        com.qwant.ci.product.id: ${CI_PRODUCT_ID}
        com.qwant.ci.project.id: ${CI_PROJECT_ID}
    image: ${CI_REGISTRY_IMAGE}:${IMAGE_TAG}
